### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tjdawngamer** [DavidHGillen/Satisfactory-AB_FluidExtras#9]
i dont know whats happening but i keep getting  Plugin 'AB_FluidExtras' failed to load because module 'AB_FluidExtras' could not be loaded.  There may be an operating system error or the module may not be properly set up.   can some one please help

**Comment by DavidHGillen** [comment]
Sorry for missing this for a while. but whenever you get an error with a mod because a mod by exactly the same name comes up, then it's not that mod. It's something in the mod loading process going screwy. Common causes are:

- Satisfactory Plus and Fluid Extras installed together as SF+ adds FE as a dependency just let it install FE rather than manually adding FE
- A deeper issue inside SML that gets blamed on any of my mods because AB is very early in the alphabet.
